site_name: Figma Documentation
site_url: https://thincutbacon.github.io/COMP-2216-Documentation/
nav: 
  - Home: index.md
  - Set Up Project: section1.md
  - Navigating Toolbar and Creating Shapes: section2.md
  - Prototyping: section3.md
  - Troubleshooting: troubleshooting.md
  - Glossary: glossary.md
markdown_extensions:
  - tables
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.blocks.caption
theme:
  name: material
  font:
    text: Roboto
    code: Source Code Pro
  features:
    - navigation.footer
  palette: 
    # Palette toggle for light mode'
    - scheme: default
      primary: lime
      accent: green
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: deep orange
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
copyright: Copyright &copy; 2025 Kiara Cherry and Kanon Nishiyama
extra_css:
  - './stylesheet/custom.css'
