site_name: My Docs
site_url: https://test.example
theme:
  name: material
  font:
    text: Roboto
    code: Source Code Pro
  palette: 
    # Palette toggle for light mode'
    - scheme: default
      primary: lime
      accent: green
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: deep orange
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode