site_name: Figma Documentation
site_url: https://test.example
nav: 
  - Home: docs/index.md
  - Set Up Project: docs/section1.md
  - Navigating Toolbar and Creating Shapes: docs/section2.md
  - Prototyping: docs/section3.md
  - Troubleshooting: docs/troubleshooting.md
  - Glossary:


theme:
  name: material
  font:
    text: Roboto
    code: Source Code Pro
  palette: 
    # Palette toggle for light mode'
    - scheme: default
      primary: lime
      accent: green
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: deep orange
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode